### ISSUE TITLE
[CDE] smoke ApiComment class. Bug #69149

### ISSUE THREAD

**Issue by askonev** [ONLYOFFICE-QA/doc-builder-testing#827]
https://github.com/ONLYOFFICE/sdkjs/commit/28de8e02c9836e11ba717124bb0f73cf98dc5e13

**Comment by askonev** [comment]
https://github.com/ONLYOFFICE/sdkjs/commit/ccbf97c4bd014ec615aaa170af6ba5d8d85e44af

**Comment by lemonowl** [comment]
Fix tests for Delete and GetUserId
